Traceback (most recent call last):
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/vkeller/.local/pipx/venvs/jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Fonction permettant de retourner la langue d'un texte donn√© en param√®tre
# sur la base d'une analyse de certains mots clefs
# La liste des mots clefs est bas√©e sur les classements internationaux (comme COCA)
# Argument 1 : le texte clair
# Retour     : une liste qui contient : [la langue possible, le nombre d'occurences des mots-clefs] 
def analyse_langue(texte):
    mots_clefs_f = ['le','la','les','un','une','de','des','il','elle','et','non','est','on','vous','nous','se','pas','leur']
    mots_clefs_a = ['the','be','to','of','and','in','that','have','it','for','not','is','if']
    retour = ['',0]
    l = len(texte)
    nbr_f = 0
    nbr_a = 0
    for mot_clef in mots_clefs_f:
        ## A REMPLIR ICI
        
    for mot_clef in mots_clefs_a:
        ## A REMPLIR ICI

    if nbr_f == 0 and nbr_a == 0:
        ## A REMPLIR ICI
        
    return retour
------------------


  [36mCell[39m[36m [39m[32mIn[6][39m[32m, line 16[39m
[31m    [39m[31mfor mot_clef in mots_clefs_a:[39m
    ^
[31mIndentationError[39m[31m:[39m expected an indented block after 'for' statement on line 13


